# Generated by Django 3.2.5 on 2021-07-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FighterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('BirthDay', models.DateField()),
                ('Location', models.CharField(max_length=200)),
                ('Weight', models.IntegerField()),
                ('MartialArt', models.CharField(max_length=200)),
                ('Gym', models.CharField(max_length=300)),
                ('Trainer', models.CharField(max_length=200)),
                ('FightRecord', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxWeight', models.IntegerField()),
                ('MinWeight', models.IntegerField()),
                ('MartialArt', models.CharField(max_length=200)),
                ('MaxDistance', models.IntegerField()),
                ('fighterprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparringsPartner24.fighterprofile')),
            ],
        ),
    ]
