# Generated by Django 3.2.5 on 2021-08-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparringsPartner24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighterprofile',
            name='Description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='fighterprofile',
            name='StartingYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='MaxExperienceYears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='MaxFights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='MinExperienceYears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='MinFights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
