# Generated by Django 3.2.5 on 2021-07-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SparringsPartner24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('MailAdress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='fighterprofile',
            name='UserName',
        ),
        migrations.RemoveField(
            model_name='searchprofile',
            name='fighterprofile',
        ),
        migrations.AddField(
            model_name='fighterprofile',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SparringsPartner24.userprofile'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SparringsPartner24.userprofile'),
        ),
    ]
