# Generated by Django 3.2.5 on 2021-07-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparringsPartner24', '0002_auto_20210725_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='MaxAge',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='MinAge',
            field=models.IntegerField(default=16),
        ),
    ]
