# Generated by Django 3.2.5 on 2021-08-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparringsPartner24', '0002_auto_20210801_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='BirthDay',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='FightRecord',
            new_name='fight_record',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='Gym',
            new_name='gym',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='MartialArt',
            new_name='martial_art',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='StartingYear',
            new_name='starting_year',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='Trainer',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='Weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MartialArt',
            new_name='martial_art',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MaxAge',
            new_name='max_age',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MaxDistance',
            new_name='max_distance',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MaxExperienceYears',
            new_name='max_experience_years',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MaxFights',
            new_name='max_fights',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MaxWeight',
            new_name='max_weight',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MinAge',
            new_name='min_age',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MinExperienceYears',
            new_name='min_experience_years',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MinFights',
            new_name='min_fights',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='MinWeight',
            new_name='min_weight',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='PhoneNumber',
            new_name='phone_number',
        ),
    ]
