# Generated by Django 3.2.5 on 2021-08-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparringsPartner24', '0003_auto_20210801_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighterprofile',
            old_name='starting_year',
            new_name='experience_years',
        ),
    ]
