# Generated by Django 3.2.5 on 2021-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparringsPartner24', '0003_auto_20210725_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='PhoneNumber',
            field=models.IntegerField(default=999),
        ),
    ]
