# Generated by Django 3.2.5 on 2021-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparringsPartner24', '0004_userprofile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighterprofile',
            name='BirthDay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='FightRecord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='Gym',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='MartialArt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='Trainer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='Weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='MartialArt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='MaxAge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='MaxDistance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='MaxWeight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='MinAge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='MinWeight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='PhoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
